@Formula1.Api_HostAddress = https://localhost:7277

### Alive

GET {{Formula1.Api_HostAddress}}/
Accept: application/json

### Alive

GET {{Formula1.Api_HostAddress}}/api
Accept: application/json

### Error

GET {{Formula1.Api_HostAddress}}/error
Accept: application/json
