@Formula1.Api_HostAddress = https://localhost:7277

### Circuits

POST {{Formula1.Api_HostAddress}}/api/circuits
Content-Type: application/json

### Constructors

POST {{Formula1.Api_HostAddress}}/api/constructors
Content-Type: application/json
{
  "fromYear": 2024,
  "toYear": 9999
}

### Drivers

POST {{Formula1.Api_HostAddress}}/api/drivers
Content-Type: application/json
{
  "fromYear": 2024,
  "toYear": 9999
}

### Races

POST {{Formula1.Api_HostAddress}}/api/races
Content-Type: application/json
{
  "fromYear": 2023,
  "toYear": 9999
}

### Seasons

POST {{Formula1.Api_HostAddress}}/api/seasons
Content-Type: application/json

###
