@Formula1.Api_HostAddress = https://localhost:7277

### Circuits

GET {{Formula1.Api_HostAddress}}/api/circuits
Accept: application/json

### 

GET {{Formula1.Api_HostAddress}}/api/circuits/a107153f-246e-4c77-b08a-0809f13b4f2f
Accept: application/json

### Races

GET {{Formula1.Api_HostAddress}}/api/races/35DD85CB-9399-4A03-A55D-3D77BB8CFD18
Accept: application/json

### Seasons

GET {{Formula1.Api_HostAddress}}/api/seasons
Accept: application/json

###

GET {{Formula1.Api_HostAddress}}/api/seasons/2023
Accept: application/json

### Sessions

GET {{Formula1.Api_HostAddress}}/api/sessions
Accept: application/json

###

GET {{Formula1.Api_HostAddress}}/api/sessions/52856ab0-d03b-40f6-a44b-4525bee6398b
Accept: application/json

### SessionTypes

GET {{Formula1.Api_HostAddress}}/api/sessiontypes
Accept: application/json

###
