@Formula1.Api_HostAddress = https://localhost:7277

### Seasons

GET {{Formula1.Api_HostAddress}}/api/seasons?pagenumber=3&pagesize=10
Accept: application/json

### Season

GET {{Formula1.Api_HostAddress}}/api/seasons/1950
Accept: application/json

### Season races

GET {{Formula1.Api_HostAddress}}/api/seasons/1951/races
Accept: application/json

### Season Constructors

GET {{Formula1.Api_HostAddress}}/api/seasons/1951/constructors
Accept: application/json

### Season Constructor Results

GET {{Formula1.Api_HostAddress}}/api/seasons/2024/constructors/6/results
Accept: application/json

### Season Drivers

GET {{Formula1.Api_HostAddress}}/api/seasons/2024/drivers
Accept: application/json

### Season Driver Results

GET {{Formula1.Api_HostAddress}}/api/seasons/2024/drivers/768/results
Accept: application/json
