@Formula1.Api_HostAddress = https://localhost:7277

### Seasons

GET {{Formula1.Api_HostAddress}}/api/seasons?pagenumber=3&pagesize=4
Accept: application/json

### Season

GET {{Formula1.Api_HostAddress}}/api/seasons/2023
Accept: application/json

### Season Constructors

GET {{Formula1.Api_HostAddress}}/api/seasons/2024/constructors
Accept: application/json

### Season Constructor Results

GET {{Formula1.Api_HostAddress}}/api/seasons/2024/constructors/1e3e6c23-ebbe-4dd7-b0af-6caa158a8ab3/results
Accept: application/json

### Season Drivers

GET {{Formula1.Api_HostAddress}}/api/seasons/2023/drivers
Accept: application/json

### Season Driver Results

GET {{Formula1.Api_HostAddress}}/api/seasons/2023/drivers/b4c1a79d-c3b1-4179-bf53-37864d22672a/results
Accept: application/json
