@Formula1.Api_HostAddress = https://localhost:7277

### Sessions

GET {{Formula1.Api_HostAddress}}/api/sessions?pagenumber=1&pagesize=12
Accept: application/json

### Session

GET {{Formula1.Api_HostAddress}}/api/sessions/1105
Accept: application/json

### Session results

GET {{Formula1.Api_HostAddress}}/api/sessions/1105/results
Accept: application/json
